#!/usr/bin/env python3
"""
bot_settings.py: the single place where the project config lives.

Replaces the old Dockerfile + envshowrun. It builds and manages the `.env`
file, and every part of the project (Flask API, Telegram bot, installer)
reads its settings from here.

Usage:
    python bot_settings.py                 # interactive setup wizard (create / edit .env)
    python bot_settings.py show            # print current config (token masked)
    python bot_settings.py get KEY         # print a single value
    python bot_settings.py set K=V [K=V..] # update values non-interactively (used by install.sh)
    python bot_settings.py run bot|flask   # run a component in the foreground with this config
"""
from __future__ import annotations

import argparse
import getpass
import os
import pathlib
import shutil
import subprocess
import sys

# ───────────────  Paths  ────────────────
BASE_DIR = pathlib.Path(__file__).resolve().parent
ENV_FILE = BASE_DIR / ".env"
DATA_DIR = BASE_DIR / "data"
BACKUP_DIR = DATA_DIR / "backups"
DB_PATH = DATA_DIR / "forexbot.db"
LOG_PATH = DATA_DIR / "bot.log"

# Website (lives in this repo, served by nginx) and the folder the bot uploads EA builds into
SITE_DIR = BASE_DIR / "website" / "content"
DOWNLOADS_DIR = SITE_DIR / "assets" / "downloads"

# ───────────────  Schema  ────────────────
# key: (default, description, secret)
FIELDS: dict[str, tuple[str, str, bool]] = {
    "RUN_FLASK":          ("true",  "Run the Flask API on this server (true/false)", False),
    "FLASK_HOST":         ("0.0.0.0", "Flask listen host", False),
    "FLASK_PORT":         ("45869", "Flask port", False),
    "FLASK_DEBUG":        ("false", "Flask debug mode (true/false)", False),
    "PUBLIC_BASE_URL":    ("",      "Public site/API URL, e.g. https://heysolo.online (optional)", False),
    "RUN_BOT":            ("false", "Run the Telegram bot on this server (true/false)", False),
    "TELEGRAM_BOT_TOKEN": ("",      "Telegram bot token", True),
    "ADMIN_CHAT_ID":      ("0",     "Admin chat ID (send /myid to the bot to find it)", False),
    "API_BASE_URL":       ("http://127.0.0.1:45869/api/forex", "Flask API base URL the bot uses", False),
    "SEND_RESTART_MSG":   ("false", "Notify all users when the bot restarts (true/false)", False),
    "BACKUP_KEEP":        ("10",    "How many backup files to keep on disk", False),
}
BOOL_KEYS = {"RUN_FLASK", "FLASK_DEBUG", "RUN_BOT", "SEND_RESTART_MSG"}
INT_KEYS = {"FLASK_PORT", "ADMIN_CHAT_ID", "BACKUP_KEEP"}


# ───────────────  .env read / write  ────────────────
def read_env(path: pathlib.Path = ENV_FILE) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        val = val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        values[key.strip()] = val
    return values


def write_env(values: dict[str, str], path: pathlib.Path = ENV_FILE) -> None:
    """Atomic write; known keys first (in schema order), unknown keys preserved after."""
    lines = ["# Generated by bot_settings.py. Edit with: python bot_settings.py"]
    for key in FIELDS:
        lines.append(f"{key}={values.get(key, FIELDS[key][0])}")
    extra = [k for k in values if k not in FIELDS]
    if extra:
        lines.append("")
        lines.append("# Extra keys")
        lines.extend(f"{k}={values[k]}" for k in extra)
    tmp = path.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(tmp, 0o600)  # contains the bot token
    os.replace(tmp, path)


def validate(key: str, value: str) -> str:
    value = value.strip()
    if key in BOOL_KEYS:
        low = value.lower()
        if low in ("true", "1", "yes", "y", "on"):
            return "true"
        if low in ("false", "0", "no", "n", "off", ""):
            return "false"
        raise ValueError(f"{key} must be true or false")
    if key in INT_KEYS:
        try:
            int(value or FIELDS[key][0])
        except ValueError:
            raise ValueError(f"{key} must be a number") from None
        return value or FIELDS[key][0]
    if key in ("API_BASE_URL", "PUBLIC_BASE_URL"):
        value = value.rstrip("/")
        if value and not value.startswith(("http://", "https://")):
            raise ValueError(f"{key} must start with http:// or https://")
    return value


# ───────────────  Legacy migration  ────────────────
def migrate_legacy_files() -> None:
    """Old versions kept forexbot.db and bot.log next to telegram_bot.py (project root)."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    for name in ("forexbot.db", "bot.log"):
        old = BASE_DIR / name
        new = DATA_DIR / name
        if old.exists() and not new.exists():
            try:
                shutil.move(str(old), str(new))
            except OSError:
                pass


# ───────────────  Runtime config (importable)  ────────────────
def _get(values: dict[str, str], key: str) -> str:
    # Real environment variables (e.g. from systemd) win over .env
    return os.environ.get(key, values.get(key, FIELDS[key][0]))


def _as_bool(v: str) -> bool:
    return str(v).strip().lower() in ("true", "1", "yes", "y", "on")


def _as_int(v: str, default: int) -> int:
    try:
        return int(str(v).strip())
    except ValueError:
        return default


def reload() -> None:
    """(Re)load config from .env into module-level constants."""
    global RUN_FLASK, FLASK_HOST, FLASK_PORT, FLASK_DEBUG, PUBLIC_BASE_URL
    global RUN_BOT, TELEGRAM_BOT_TOKEN, ADMIN_CHAT_ID, API_BASE_URL
    global SEND_RESTART_MSG, BACKUP_KEEP
    v = read_env()
    RUN_FLASK = _as_bool(_get(v, "RUN_FLASK"))
    FLASK_HOST = _get(v, "FLASK_HOST") or "0.0.0.0"
    FLASK_PORT = _as_int(_get(v, "FLASK_PORT"), 45869)
    FLASK_DEBUG = _as_bool(_get(v, "FLASK_DEBUG"))
    PUBLIC_BASE_URL = _get(v, "PUBLIC_BASE_URL")
    RUN_BOT = _as_bool(_get(v, "RUN_BOT"))
    TELEGRAM_BOT_TOKEN = _get(v, "TELEGRAM_BOT_TOKEN")
    ADMIN_CHAT_ID = _as_int(_get(v, "ADMIN_CHAT_ID"), 0)
    API_BASE_URL = _get(v, "API_BASE_URL").rstrip("/")
    SEND_RESTART_MSG = _as_bool(_get(v, "SEND_RESTART_MSG"))
    BACKUP_KEEP = max(1, _as_int(_get(v, "BACKUP_KEEP"), 10))


migrate_legacy_files()
reload()


# ───────────────  CLI  ────────────────
def _mask(key: str, value: str) -> str:
    if FIELDS.get(key, ("", "", False))[2] and value:
        return value[:4] + "…" + value[-4:] if len(value) > 10 else "****"
    return value


def cmd_show(_args) -> int:
    values = read_env()
    print(f"Config file: {ENV_FILE}{'' if ENV_FILE.exists() else '  (not created yet)'}")
    print(f"Data dir:    {DATA_DIR}")
    print("-" * 60)
    width = max(len(k) for k in FIELDS)
    for key, (default, desc, _secret) in FIELDS.items():
        val = values.get(key, default)
        print(f"{key.ljust(width)} = {_mask(key, val)}")
    for key in values:
        if key not in FIELDS:
            print(f"{key.ljust(width)} = {values[key]}  (extra)")
    return 0


def cmd_get(args) -> int:
    values = read_env()
    if args.key not in values and args.key not in FIELDS:
        return 1
    print(values.get(args.key, FIELDS.get(args.key, ("",))[0]))
    return 0


def cmd_set(args) -> int:
    values = read_env()
    for pair in args.pairs:
        if "=" not in pair:
            print(f"Invalid pair (expected KEY=VALUE): {pair}", file=sys.stderr)
            return 2
        key, val = pair.split("=", 1)
        key = key.strip()
        try:
            values[key] = validate(key, val) if key in FIELDS else val
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            return 2
    write_env(values)
    print(f"✓ Saved {ENV_FILE}")
    return 0


def _ask(key: str, current: str) -> str:
    default, desc, secret = FIELDS[key]
    while True:
        if secret:
            hint = " (Enter = keep current)" if current else ""
            raw = getpass.getpass(f"{desc}{hint}: ")
        elif key in BOOL_KEYS:
            cur = _as_bool(current)
            raw = input(f"{desc} [{'Y/n' if cur else 'y/N'}]: ")
            raw = raw or ("true" if cur else "false")
        else:
            raw = input(f"{desc} [{current}]: ")
        raw = raw if raw.strip() else current
        try:
            return validate(key, raw)
        except ValueError as e:
            print(f"  ✗ {e}")


def _restart_services(values: dict[str, str]) -> None:
    if not shutil.which("systemctl"):
        return
    units = []
    if _as_bool(values.get("RUN_FLASK", "true")) and pathlib.Path("/etc/systemd/system/flask.service").exists():
        units.append("flask.service")
    if _as_bool(values.get("RUN_BOT", "false")) and pathlib.Path("/etc/systemd/system/telegram-bot.service").exists():
        units.append("telegram-bot.service")
    if not units:
        return
    if input(f"Restart {', '.join(units)} now to apply? [Y/n]: ").strip().lower() in ("", "y", "yes"):
        subprocess.call(["systemctl", "restart", *units])
        print("✓ Restarted")


def cmd_setup(_args) -> int:
    values = read_env()
    cur = lambda k: values.get(k, FIELDS[k][0])  # noqa: E731
    print("=== ForexFactory bot settings ===")
    print(f"Writing to {ENV_FILE}\n")

    values["RUN_FLASK"] = _ask("RUN_FLASK", cur("RUN_FLASK"))
    if values["RUN_FLASK"] == "true":
        for k in ("FLASK_PORT", "PUBLIC_BASE_URL"):
            values[k] = _ask(k, cur(k))

    values["RUN_BOT"] = _ask("RUN_BOT", cur("RUN_BOT"))
    if values["RUN_BOT"] == "true":
        for k in ("TELEGRAM_BOT_TOKEN", "ADMIN_CHAT_ID"):
            values[k] = _ask(k, cur(k))
        api_default = cur("API_BASE_URL")
        if values["RUN_FLASK"] == "true":
            api_default = f"http://127.0.0.1:{values.get('FLASK_PORT', '45869')}/api/forex"
        values["API_BASE_URL"] = _ask("API_BASE_URL", api_default)
        for k in ("SEND_RESTART_MSG", "BACKUP_KEEP"):
            values[k] = _ask(k, cur(k))


    write_env(values)
    print(f"\n✓ Saved {ENV_FILE}\n")
    cmd_show(None)
    _restart_services(values)
    return 0


def cmd_run(args) -> int:
    target = {"bot": BASE_DIR / "bot" / "telegram_bot.py",
              "flask": BASE_DIR / "api" / "flask_server.py"}[args.component]
    env = dict(os.environ)
    env.update(read_env())
    if args.component == "bot":
        env["RUN_BOT"] = "true"
    return subprocess.call([sys.executable, str(target)], cwd=str(BASE_DIR), env=env)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Manage the ForexFactory bot / API config (.env)")
    sub = p.add_subparsers(dest="cmd")
    sub.add_parser("setup", help="interactive setup wizard (default)")
    sub.add_parser("show", help="show current config")
    g = sub.add_parser("get", help="print one value")
    g.add_argument("key")
    s = sub.add_parser("set", help="set KEY=VALUE pairs")
    s.add_argument("pairs", nargs="+")
    r = sub.add_parser("run", help="run a component in the foreground")
    r.add_argument("component", choices=["bot", "flask"])
    args = p.parse_args(argv)
    handlers = {None: cmd_setup, "setup": cmd_setup, "show": cmd_show,
                "get": cmd_get, "set": cmd_set, "run": cmd_run}
    try:
        return handlers[args.cmd](args)
    except (KeyboardInterrupt, EOFError):
        print("\nCancelled.")
        return 130


if __name__ == "__main__":
    sys.exit(main())
